name: ScanProcedure CI

on: 
  push:
    branches:
      - master
      - development

  pull_request:
    branches:
      - master
      - development

jobs: 
  build:
    name: Build ScanProcedure Application
    runs-on: windows-2025

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        uses: dotnet restore ScanProcedure.sln

      - name: Build
        uses: dotnet build ScanProcedure.sln --configuration Release --no-restore

      - name: Test
        uses: dotnet test ScanProcedure.sln --configuration Release --no-build

      - name: Publish
        uses: dotnet publish ScanProcedure/ScanProcedure.sln --configuration Release --output ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScanProcedure-${{github.sha}}
          path: ./publish

      
      
